[st_calculation]
start = -9
end = 1

[st_plotting]
top_n = 3  # Number of top-eigenvectors to be plotted
plot_folder = "plots"  # directory for all plots using RF-plotting

[unit_processor]
# Processing
dt = 0.01
save_plots = false
max_per_row = 5
export_enabled = true

# Behaviour
center = false
plotting = false


# Filter criteria
min_spikes_in_window = 500

# Paths
h5_dir = "exp_data/h5_halffield"  # spike-data (usually something with spikes_only)
led_dir = "exp_data/led_halffield"  # directory of synced .npz led data
export_dir = "export"  # where the numerical STA values should be saved
plot_dir = "plots"  # used for all plots during unit_processor
log_dir = "logs"



# RF Extras
fraction_spikes = 1.0